# Generated by Django 4.1.9 on 2023-08-15 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        ('person', '0001_initial'),
        ('products', '0002_alter_product_type'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ticket_no', models.CharField(max_length=100)),
                ('do', models.CharField(max_length=100)),
                ('weight_in', models.IntegerField(default=0)),
                ('weight_out', models.IntegerField(default=0)),
                ('deduction', models.IntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('driver', models.ForeignKey(limit_choices_to={'type': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.person')),
                ('from_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_destination', to='destinations.destination')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('to_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_destination', to='destinations.destination')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
            ],
        ),
    ]
