# Generated by Django 4.1.9 on 2023-08-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_inventory_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='supplier_qty',
            field=models.IntegerField(default=0),
        ),
    ]
