# Generated by Django 4.1.9 on 2023-12-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_inventory_bucket_inventory_customer_ticket_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='bucket',
            field=models.FloatField(default=0.0),
        ),
    ]
